name: tp0-Tom
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
  
  validador:
    container_name: validador
    entrypoint: ["/bin/sh", "./validar_echo_server.sh"]
    image: alpine:latest
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - /validar_echo_server.sh:/validar_echo_server.sh
    - ./server/config.ini:/config.ini
