name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - NOMBRE=client1
    - APELLIDO=client1
    - DOCUMENTO=23322511
    - NACIMIENTO=1985-10-18
    - NUMERO=32
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/agency-1.csv:/agency.csv
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
